import type { Metadata } from "next";
import "./globals.css";
import { Inter, Playfair_Display } from "next/font/google";
import IndexNav from "@/components/IndexNav";
import CursorGlow from "@/components/CursorGlow";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-heading",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Judith Yusuf",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
    openGraph: {
    title: "Judith Yusuf",
    description: "Judith Yusuf - Frontend Engineer",
    url: "https://judithyusuf.vercel.app",
    siteName: "Judith Yusuf - Frontend Engineer",
    images: [
      { url: "https://judithyusuf.vercel.app/og.png", alt: "Judith Yusuf" },
    ],
    type: "website",
  },
  twitter: {
    title: "Judith Yusuf",
    description: "Judith Yusuf - Frontend Engineer",
    images: [
      { url: "https://judithyusuf.vercel.app/og.png", alt: "Judith Yusuf" },
    ],
    card: "summary_large_image",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased bg-background w-full md:flex ${inter.variable} ${playfair.variable}`}
      >
        <CursorGlow />
        <IndexNav />
        {children}
      </body>
    </html>
  );
}
